apiVersion: v1
kind: Service
metadata:
  name: k8s-webapp
  namespace: development
spec:
  selector:
    app: k8s-webapp
  ports:
  - port: 5000    
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-webapp
  namespace: development
spec:
  selector:
    matchLabels:
      app: k8s-webapp
  template:
    metadata:
      labels:
        app: k8s-webapp
    spec:
      containers:
      - name: k8s-webapp
        image: gematt/k8s-webapp:0.1.5
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80        
        env:
        - name: ApiUrl
          value: "http://k8s-webapi"
        - name: VaultUri
          value: "https://k8skvault.vault.azure.net/"
        - name: AzureSignalRConnectionString
          value: "Endpoint=https://k8ssignalr.service.signalr.net; ***"
  replicas: 2

---

# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: webapp-ingress
#   namespace: development
#   labels:
#     name: webapp-ingress
# spec:
#   # tls:
#   # - hosts:
#   #   - webapp.localdev.me
#   #   secretName: k8s-webapp-tls
#   rules:
#   - host: webapp.localdev.me
#     http:
#       paths:
#       - pathType: Prefix
#         path: /
#         backend:
#           service:
#             name: k8s-webapp
#             port: 
#               number: 80
  # - host: webapp2.localdev.me
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: /
  #       backend:
  #         service:
  #           name: k8s-webapp
  #           port: 
  #             number: 80