apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-url: mongo-service  

---

apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy # base64 encoded value of "mongouser". Use echo -n 'mongouser' | base64
  mongo-password: bW9uZ29wYXNzd29yZA== # base64 encoded value of "my_password". Use echo -n 'my_password' | base64

